### ISSUE TITLE
Problems installing version 0.3.3

### ISSUE THREAD

**Issue by JJ** [perl6/Pod-To-Cached#2]
@coke reports [here](https://github.com/finanalyst/pod-cached/issues/25) a failure to install the version released to the ecosystem.It's likely that there are some problems in that version, since we have been working mainly with our local versions. I can't see any error in the current version in master, which is why I've upgraded to 0.3.4 here.
@coke, can you please check with the version in master and report back to us? If this one is OK, we'll make the switch to this version ASAP.

**Comment by antoniogamiz** [comment]
Maybe we should delete this one from the ecosystem and leave only the official.

**Comment by JJ** [comment]
Apparently these problems have been fixed in version 0.3.5. Closing. Also, this one has been published in the ecosystem, superseding the old one.
